- name: Copy keys to CC
  action: copy src=/tmp/{{ item }} dest=/var/lib/eucalyptus/keys/ owner=eucalyptus group=eucalyptus mode=0700
  with_items:
  - cluster-cert.pem
  - cluster-pk.pem
  - node-cert.pem
  - node-pk.pem
  - cloud-pk.pem
  - cloud-cert.pem
#  when: not inventory_hostname in groups.clc 

- name: Restart CC
  action: service name=eucalyptus-cc state=restarted

- name: Restart CLC
  action: service name=eucalyptus-cloud state=restarted
  when: inventory_hostname in groups.clc

- name: Wait for service
  action: wait_for port=8774 delay=15

#- name: Check Registration of nodes
#  action: command /usr/sbin/euca_conf --list-nodes | grep -q ${hostvars.{$item}.ansible_$bridge.ipv4.address}
#  with_items: ${groups.nc}
#  ignore_errors: yes
#  register: check_nodes
#  tags:
#  - nodereg

#- name: Registering nodes
#  action: command /usr/sbin/euca_conf --no-scp --no-rsync --no-sync --register-nodes ${hostvars.{$item}.ansible_$bridge.ipv4.address}
#  with_items: ${groups.nc}
#  only_if: "'${check_nodes.rc}' == '1'"
#  tags:
#  - nodereg
