    - name: set tuned profile
      action: command tuned-adm profile enterprise-storage

    - name: Install the SC packages
      action: yum name=eucalyptus-sc state=present

    - name: Template the configuration file
      action: template src=../../common/templates/eucalyptus.conf.j2 dest=/etc/eucalyptus/eucalyptus.conf
      notify: restart eucalyptus cloud

